### PR TITLE
People List Filter Labels as a Global Setting

### PR DESCRIPTION
**Pull request by patrickbrown-io**
Changes the People List `Filter 1`, `Filter 2`, and `Filter 3` custom labels to a Global Setting in Site Configuration, rather than being set per-page. These labels will be set under Configuration => Cu Boulder Site Settings => Appearance and Layout.

Resolves [#543 ](https://github.com/CuBoulder/tiamat-theme/issues/543)

Includes:
- `ucb_site_configuarion` => https://github.com/CuBoulder/ucb_site_configuration/pull/35
-  `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/560
-  `ucb_custom_entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/87

### CODE REVIEW

**Comment by timurtripp** [comment]
Does It make more sense to have them under "Pages and search" instead of "Appearance and layout"?

**Comment by timurtripp** [comment]
"Related articles" could be put under there too as part of a future update.

**Comment by timurtripp** [comment]
Unfortunately having them be theme settings makes it harder to move them out of "Appearance and layout" in the future.

**Comment by patrickbrown-io** [comment]
> Does It make more sense to have them under "Pages and search" instead of "Appearance and layout"?

@timurtripp "Appearance and Layout" has the other display settings for choosing Article Date Formats, where things should render, etc so it seemed more appropriate since its just a display label. 

Probably up to @jcsparks or @kevincrafts

**Comment by timurtripp** [comment]
> > Does It make more sense to have them under "Pages and search" instead of "Appearance and layout"?
> 
> @timurtripp "Appearance and Layout" has the other display settings for choosing Article Date Formats, where things should render, etc so it seemed more appropriate since its just a display label.
> 
> Probably up to @jcsparks or @kevincrafts

Does that setting only affect articles? I was actually confused about whether that should be moved as well.

**Comment by timurtripp** [comment]
GTM account number doesn't belong there either but was a holdover from the old theme settings before site configuration existed as a module. I will bring that one up with Jeremey at some point.

**Comment by patrickbrown-io** [comment]
> > > Does It make more sense to have them under "Pages and search" instead of "Appearance and layout"?
> > 
> > 
> > @timurtripp "Appearance and Layout" has the other display settings for choosing Article Date Formats, where things should render, etc so it seemed more appropriate since its just a display label.
> > Probably up to @jcsparks or @kevincrafts
> 
> Does that setting only affect articles? I was actually confused about whether that should be moved as well.

Currently I think Articles are the only content that actually use that setting to do something

**Comment by timurtripp** [comment]
> > > > Does It make more sense to have them under "Pages and search" instead of "Appearance and layout"?
> > > 
> > > 
> > > @timurtripp "Appearance and Layout" has the other display settings for choosing Article Date Formats, where things should render, etc so it seemed more appropriate since its just a display label.
> > > Probably up to @jcsparks or @kevincrafts
> > 
> > 
> > Does that setting only affect articles? I was actually confused about whether that should be moved as well.
> 
> Currently I think Articles are the only content that actually use that setting to do something

Gotcha. I don't like that it's ambiguous when a setting applies to only a single page type.

**Comment by timurtripp** [comment]
Actually, now that "General" is accessible to site managers, I'd reorganize this a bit by moving the stuff currently under "Pages and search" into "General" and repurposing that tab for things specific to a single page type. That's a future issue but try not to make these theme settings which will make it easier to reorganize in the future.

**Comment by timurtripp** [comment]
On second thought I could write an update hook to perform the conversion from theme setting to module setting when I move them out of "Appearance and layout", it's just more work.

**Comment by patrickbrown-io** [comment]
> Actually, now that "General" is accessible to site managers, I'd reorganize this a bit by moving the stuff currently under "Pages and search" into "General" and repurposing that tab for things specific to a single page type. That's a future issue but try not to make these theme settings and instead module settings which will make it easier to reorganize in the future.

Just made a new issue for this
https://github.com/CuBoulder/ucb_site_configuration/issues/36

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
